#vyos-get-version.yml - Get version
#v1.1 - 2021-01-29
#ansible-playbook -vv -i inventory.yml vyos-get-version.yml

- name: VyOS - Get Version Detail
  hosts: routers
  tasks:
    - name: Get config for VyOS devices
      vyos_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
