routers:
  hosts:
    vyos-1:
      ansible_host: 192.168.X.1
    vyos-2:
      ansible_host: 192.168.X.2
    vyos-3:
      ansible_host: 192.168.X.3
    vyos-4:
      ansible_host: 192.168.X.4
    vyos-5:
      ansible_host: 192.168.X.5
