interfaces:
  - vyos_if: "eth0"
    desc: "Net12"
    ipv4_addr: "172.Y.12.1/24"
    enabled: "true"    
    
  - vyos_if: "eth1"
    desc: "Net6"
    ipv4_addr: "172.Y.6.2/24"
    enabled: "true"

  - vyos_if: "eth2"
    desc: "Net2"
    ipv4_addr: "172.Y.2.254/24"
    enabled: "true"

dhcp_pools: 
  - dhcp: true
    dhcp_subnet: "172.Y.2.0/24"
    dhcp_poolname: "NETWORK2"
    dhcp_range1: "N2-RANGE2"
    dhcp_range1_start: "172.Y.2.100"
    dhcp_range1_stop: "172.Y.2.200"
    dhcp_dns1: "132.235.9.75"
    dhcp_dns2: "132.235.200.41"
    dhcp_default_router: "172.Y.2.254"
    dhcp_lease_time: "120"
    
routes:
  - ospf: true
    ospf_area: "0"
    ospf_network: "172.Y.0.0/17"
    ospf_metric: "2"
    ospf_route_map_name: "CONNECT"
    ospf_route_map_rule: "10"
    ospf_route_map_action: "permit"
    ospf_route_map_match_interface: "lo"
